/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextRouteImport } from './routes/text'
import { Route as SimulatorSetupRouteImport } from './routes/simulator-setup'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CirclesIndexRouteImport } from './routes/circles.index'
import { Route as CirclesIdRouteImport } from './routes/circles.$id'

const TextRoute = TextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorSetupRoute = SimulatorSetupRouteImport.update({
  id: '/simulator-setup',
  path: '/simulator-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIdRoute = CirclesIdRouteImport.update({
  id: '/circles/$id',
  path: '/circles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/app': typeof AppRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/recovery': typeof RecoveryRoute
  '/simulator': typeof SimulatorRoute
  '/simulator-setup': typeof SimulatorSetupRoute
  '/text': typeof TextRoute
  '/circles/$id': typeof CirclesIdRoute
  '/circles/': typeof CirclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/app': typeof AppRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/recovery': typeof RecoveryRoute
  '/simulator': typeof SimulatorRoute
  '/simulator-setup': typeof SimulatorSetupRoute
  '/text': typeof TextRoute
  '/circles/$id': typeof CirclesIdRoute
  '/circles': typeof CirclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/app': typeof AppRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/recovery': typeof RecoveryRoute
  '/simulator': typeof SimulatorRoute
  '/simulator-setup': typeof SimulatorSetupRoute
  '/text': typeof TextRoute
  '/circles/$id': typeof CirclesIdRoute
  '/circles/': typeof CirclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyst'
    | '/app'
    | '/insights'
    | '/onboarding'
    | '/premium'
    | '/recovery'
    | '/simulator'
    | '/simulator-setup'
    | '/text'
    | '/circles/$id'
    | '/circles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyst'
    | '/app'
    | '/insights'
    | '/onboarding'
    | '/premium'
    | '/recovery'
    | '/simulator'
    | '/simulator-setup'
    | '/text'
    | '/circles/$id'
    | '/circles'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/app'
    | '/insights'
    | '/onboarding'
    | '/premium'
    | '/recovery'
    | '/simulator'
    | '/simulator-setup'
    | '/text'
    | '/circles/$id'
    | '/circles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRoute: typeof AnalystRoute
  AppRoute: typeof AppRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  RecoveryRoute: typeof RecoveryRoute
  SimulatorRoute: typeof SimulatorRoute
  SimulatorSetupRoute: typeof SimulatorSetupRoute
  TextRoute: typeof TextRoute
  CirclesIdRoute: typeof CirclesIdRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator-setup': {
      id: '/simulator-setup'
      path: '/simulator-setup'
      fullPath: '/simulator-setup'
      preLoaderRoute: typeof SimulatorSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$id': {
      id: '/circles/$id'
      path: '/circles/$id'
      fullPath: '/circles/$id'
      preLoaderRoute: typeof CirclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRoute: AnalystRoute,
  AppRoute: AppRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  RecoveryRoute: RecoveryRoute,
  SimulatorRoute: SimulatorRoute,
  SimulatorSetupRoute: SimulatorSetupRoute,
  TextRoute: TextRoute,
  CirclesIdRoute: CirclesIdRoute,
  CirclesIndexRoute: CirclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
